AVUTIL_COMM_FILES := \
			libavutil/adler32.c			\
			libavutil/avstring.c		\
			libavutil/base64.c			\
			libavutil/bprint.c			\
			libavutil/buffer.c			\
			libavutil/channel_layout.c  \
			libavutil/color_utils.c		\
			libavutil/cpu.c				\
			libavutil/crc.c				\
			libavutil/des.c				\
			libavutil/dict.c			\
			libavutil/display.c			\
			libavutil/error.c			\
			libavutil/eval.c			\
			libavutil/fifo.c			\
			libavutil/file_open.c		\
			libavutil/fixed_dsp.c   	\
			libavutil/float_dsp.c    	\
			libavutil/frame.c    		\
			libavutil/hash.c    		\
			libavutil/hmac.c    		\
			libavutil/imgutils.c    	\
			libavutil/integer.c    		\
			libavutil/intmath.c    		\
			libavutil/lls.c    			\
			libavutil/log.c   			\
			libavutil/log2_tab.c    	\
			libavutil/mastering_display_metadata.c    \
			libavutil/mathematics.c    	\
			libavutil/md5.c    			\
			libavutil/mem.c    			\
			libavutil/murmur3.c    		\
			libavutil/opt.c    			\
			libavutil/parseutils.c    	\
			libavutil/pixdesc.c    		\
			libavutil/pixelutils.c    	\
			libavutil/random_seed.c    	\
			libavutil/rational.c    	\
			libavutil/reverse.c    		\
			libavutil/ripemd.c    		\
			libavutil/samplefmt.c    	\
			libavutil/sha.c    			\
			libavutil/sha512.c    		\
			libavutil/spherical.c    	\
			libavutil/stereo3d.c    	\
			libavutil/time.c    		\
			libavutil/timecode.c    	\
			libavutil/utils.c    		\
			
AVUTIL_ARM_FILES := \
			libavutil/arm/asm.S						\
			libavutil/arm/cpu.c						\
			libavutil/arm/float_dsp_init_arm.c		\
			libavutil/arm/float_dsp_init_neon.c		\
			libavutil/arm/float_dsp_init_vfp.c		\
			libavutil/arm/float_dsp_neon.S			\
			libavutil/arm/float_dsp_vfp.S			\

AVUTIL_X86_FILES := \
			libavutil/x86/cpu.c						\
			libavutil/x86/float_dsp_init.c			\
			libavutil/x86/fixed_dsp_init.c			\
			libavutil/x86/lls_init.c				\



AVCODEC_COMM_FILES := \
			libavcodec/allcodecs.c					\
			libavcodec/avdct.c						\
			libavcodec/avpacket.c					\
			libavcodec/avpicture.c					\
			libavcodec/bitstream.c					\
			libavcodec/bswapdsp.c \
			libavcodec/cabac.c    \
			libavcodec/codec_desc.c    \
			libavcodec/d3d11va.c    \
			libavcodec/dirac.c    \
			libavcodec/error_resilience.c    \
			libavcodec/fft_fixed_32.c    \
			libavcodec/fft_fixed.c    \
			libavcodec/fft_init_table.c    \
			libavcodec/fft_float.c    \
			libavcodec/faandct.c    \
			libavcodec/faanidct.c    \
			libavcodec/fdctdsp.c    \
			libavcodec/golomb.c    \
			libavcodec/h2645_parse.c    \
			libavcodec/h264chroma.c    \
			libavcodec/h264data.c    \
			libavcodec/h264dec.c    \
			libavcodec/h264dsp.c    \
			libavcodec/h264idct.c    \
			libavcodec/h264pred.c    \
			libavcodec/h264qpel.c    \
			libavcodec/h264_cabac.c    \
			libavcodec/h264_cavlc.c    \
			libavcodec/h264_direct.c    \
			libavcodec/h264_loopfilter.c    \
			libavcodec/h264_mb.c    \
			libavcodec/h264_parse.c    \
			libavcodec/h264_picture.c    \
			libavcodec/h264_ps.c    \
			libavcodec/h264_refs.c    \
			libavcodec/h264_sei.c    \
			libavcodec/h264_slice.c    \
			libavcodec/hevc.c    \
			libavcodec/hevcdsp.c    \
			libavcodec/hevcpred.c    \
			libavcodec/hevc_cabac.c    \
			libavcodec/hevc_data.c    \
			libavcodec/hevc_filter.c    \
			libavcodec/hevc_mvs.c    \
			libavcodec/hevc_parse.c    \
			libavcodec/hevc_ps.c    \
			libavcodec/hevc_refs.c    \
			libavcodec/hevc_sei.c    \
			libavcodec/idctdsp.c    \
			libavcodec/jfdctfst.c    \
			libavcodec/jfdctint.c    \
			libavcodec/jrevdct.c    \
			libavcodec/mathtables.c    \
			libavcodec/mediacodec.c    \
			libavcodec/me_cmp.c    \
			libavcodec/mjpegenc_huffman.c    \
			libavcodec/options.c    \
			libavcodec/pixblockdsp.c    \
			libavcodec/profiles.c    \
			libavcodec/pthread.c    \
			libavcodec/pthread_frame.c    \
			libavcodec/pthread_slice.c    \
			libavcodec/simple_idct.c    \
			libavcodec/startcode.c    \
			libavcodec/utils.c    \
			libavcodec/videodsp.c    \
			libavcodec/aacadtsdec.c   \
			libavcodec/aacdec.c   \
			libavcodec/aacps_float.c  \
			libavcodec/aacpsdsp_float.c  \
			libavcodec/aacsbr.c  \
			libavcodec/aactab.c  \
			libavcodec/avfft.c  \
			libavcodec/cbrt_data.c  \
			libavcodec/dct.c  \
			libavcodec/dct32_fixed.c  \
			libavcodec/dct32_float.c  \
			libavcodec/kbdwin.c  \
			libavcodec/latm_parser.c  \
			libavcodec/mdct15.c  \
			libavcodec/mdct_fixed.c  \
			libavcodec/mdct_fixed_32.c  \
			libavcodec/mdct_float.c  \
			libavcodec/mpeg4audio.c  \
			libavcodec/mpegaudio.c  \
			libavcodec/mpegaudiodata.c  \
			libavcodec/mpegaudiodec_fixed.c  \
			libavcodec/mpegaudiodecheader.c  \
			libavcodec/mpegaudiodsp.c  \
			libavcodec/mpegaudiodsp_data.c  \
			libavcodec/mpegaudiodsp_fixed.c  \
			libavcodec/mpegaudiodsp_float.c  \
			libavcodec/parser.c  					\
			libavcodec/rdft.c 						\
			libavcodec/sbrdsp.c  					\
			libavcodec/sinewin.c  					\
			libavcodec/sinewin_fixed.c  			\
			libavcodec/raw.c  						\
			libavcodec/rawdec.c  					\
			libavcodec/bsf.c  						\
			libavcodec/aac_ac3_parser.c  			\
			libavcodec/aac_parser.c  				\
			libavcodec/bitstream_filter.c  			\
			libavcodec/bitstream_filters.c  		\
			libavcodec/mpegaudio_parser.c  			\
			libavcodec/mp3_header_decompress_bsf.c 	\
			QCP/qcCodec.c 							\
			QCP/qcEncoder.c 							\
			QCP/qcFFLog.c							\

AVCODEC_ARM_FILES := \
			libavcodec/arm/blockdsp_init_arm.c    \
			libavcodec/arm/blockdsp_init_neon.c    \
			libavcodec/arm/blockdsp_neon.S    \
			libavcodec/arm/fft_fixed_init_arm.c    \
			libavcodec/arm/fft_fixed_neon.S    \
			libavcodec/arm/fft_init_arm.c    \
			libavcodec/arm/fft_neon.S    \
			libavcodec/arm/fft_vfp.S    \
			libavcodec/arm/flacdsp_arm.S    \
			libavcodec/arm/flacdsp_init_arm.c    \
			libavcodec/arm/fmtconvert_init_arm.c    \
			libavcodec/arm/fmtconvert_neon.S    \
			libavcodec/arm/fmtconvert_vfp.S    \
			libavcodec/arm/h264chroma_init_arm.c    \
			libavcodec/arm/h264cmc_neon.S    \
			libavcodec/arm/h264dsp_init_arm.c    \
			libavcodec/arm/h264dsp_neon.S    \
			libavcodec/arm/h264idct_neon.S    \
			libavcodec/arm/h264pred_init_arm.c    \
			libavcodec/arm/h264pred_neon.S    \
			libavcodec/arm/h264qpel_init_arm.c    \
			libavcodec/arm/h264qpel_neon.S    \
			libavcodec/arm/hevcdsp_deblock_neon.S    \
			libavcodec/arm/hevcdsp_idct_neon.S    \
			libavcodec/arm/hevcdsp_init_arm.c    \
			libavcodec/arm/hevcdsp_init_neon.c    \
			libavcodec/arm/hevcdsp_qpel_neon.S    \
			libavcodec/arm/hpeldsp_arm.S    \
			libavcodec/arm/hpeldsp_armv6.S    \
			libavcodec/arm/hpeldsp_init_arm.c    \
			libavcodec/arm/hpeldsp_init_armv6.c    \
			libavcodec/arm/hpeldsp_init_neon.c    \
			libavcodec/arm/hpeldsp_neon.S    \
			libavcodec/arm/idctdsp_arm.S    \
			libavcodec/arm/idctdsp_armv6.S    \
			libavcodec/arm/idctdsp_init_arm.c    \
			libavcodec/arm/idctdsp_init_armv5te.c    \
			libavcodec/arm/idctdsp_init_armv6.c    \
			libavcodec/arm/idctdsp_init_neon.c    \
			libavcodec/arm/idctdsp_neon.S    \
			libavcodec/arm/int_neon.S    \
			libavcodec/arm/jrevdct_arm.S    \
			libavcodec/arm/mdct_fixed_neon.S    \
			libavcodec/arm/mdct_neon.S    \
			libavcodec/arm/mdct_vfp.S    \
			libavcodec/arm/me_cmp_armv6.S    \
			libavcodec/arm/me_cmp_init_arm.c    \
			libavcodec/arm/mpegvideoencdsp_armv6.S    \
			libavcodec/arm/mpegvideoencdsp_init_arm.c    \
			libavcodec/arm/mpegvideo_arm.c    \
			libavcodec/arm/mpegvideo_armv5te.c    \
			libavcodec/arm/mpegvideo_armv5te_s.S    \
			libavcodec/arm/mpegvideo_neon.S    \
			libavcodec/arm/neon.S    \
			libavcodec/arm/pixblockdsp_armv6.S    \
			libavcodec/arm/pixblockdsp_init_arm.c    \
			libavcodec/arm/rdft_init_arm.c    \
			libavcodec/arm/rdft_neon.S    \
			libavcodec/arm/simple_idct_arm.S    \
			libavcodec/arm/simple_idct_armv5te.S    \
			libavcodec/arm/simple_idct_armv6.S    \
			libavcodec/arm/simple_idct_neon.S    \
			libavcodec/arm/startcode_armv6.S    \
			libavcodec/arm/videodsp_armv5te.S    \
			libavcodec/arm/videodsp_init_arm.c    \
			libavcodec/arm/videodsp_init_armv5te.c    \
			libavcodec/arm/aacpsdsp_init_arm.c 		\
			libavcodec/arm/aacpsdsp_neon.S 			\
			libavcodec/arm/audiodsp_init_arm.c 		\
			libavcodec/arm/audiodsp_init_neon.c 	\
			libavcodec/arm/audiodsp_neon.S 			\
			libavcodec/arm/mpegaudiodsp_init_arm.c 		\
			libavcodec/arm/mpegaudiodsp_fixed_armv6.S	\
			libavcodec/arm/sbrdsp_init_arm.c 			\
			libavcodec/arm/sbrdsp_neon.S				\

AVCODEC_X86_FILES := \
			libavcodec/x86/blockdsp_init.c    		\
			libavcodec/x86/bswapdsp_init.c    		\
			libavcodec/x86/fft_init.c    			\
			libavcodec/x86/fdctdsp_init.c    		\
			libavcodec/x86/h264chroma_init.c    	\
			libavcodec/x86/h264dsp_init.c 			\
			libavcodec/x86/h264_intrapred_init.c 	\
			libavcodec/x86/h264_qpel.c  			\
			libavcodec/x86/hevcdsp_init.c 			\
			libavcodec/x86/idctdsp_init.c 			\
			libavcodec/x86/me_cmp_init.c 			\
			libavcodec/x86/pixblockdsp_init.c 		\
			libavcodec/x86/videodsp_init.c 			\
			libavcodec/x86/aacpsdsp_init.c 			\
			libavcodec/x86/audiodsp_init.c 			\
			libavcodec/x86/dct_init.c 				\
			libavcodec/x86/mpegaudiodsp.c 			\
			libavcodec/x86/sbrdsp_init.c 			\
	
AVFORMAT_COMM_FILES := \
			libavformat/aacdec.c					\
			libavformat/allformats.c				\
			libavformat/avio.c						\
			libavformat/aviobuf.c					\
			libavformat/dump.c						\
			libavformat/file.c						\
			libavformat/format.c					\
			libavformat/http.c						\
			libavformat/httpauth.c					\
			libavformat/id3v1.c						\
			libavformat/id3v2.c						\
			libavformat/metadata.c					\
			libavformat/mp3dec.c					\
			libavformat/network.c					\
			libavformat/options.c					\
			libavformat/os_support.c				\
			libavformat/protocols.c					\
			libavformat/qtpalette.c					\
			libavformat/rawdec.c					\
			libavformat/replaygain.c				\
			libavformat/sdp.c						\
			libavformat/tcp.c						\
			libavformat/url.c						\
			libavformat/urldecode.c					\
			libavformat/utils.c						\
			QCP/qcFormat.cpp 						\
			QCP/CBaseFFParser.cpp 					\
			QCP/CFFMpegParser.cpp 					\
			QCP/CFFMpegInIO.cpp 					\
			QCP/CFFMpegIO.cpp 						\
			QCP/CFFBaseIO.cpp 						\
			QCP/qcFFIO.cpp 							\

AVCODEC_MJPEG_FILES := \
			libavcodec/aandcttab.c    				\
			libavcodec/blockdsp.c   				\
			libavcodec/exif.c   					\
			libavcodec/frame_thread_encoder.c    	\
			libavcodec/hpeldsp.c    				\
			libavcodec/imgconvert.c    				\
			libavcodec/jpegtables.c    				\
			libavcodec/mjpeg_parser.c    			\
			libavcodec/mjpegdec.c    				\
			libavcodec/mjpegenc.c    				\
			libavcodec/mjpegenc_common.c    		\
			libavcodec/motion_est.c    				\
			libavcodec/mpeg12data.c    				\
			libavcodec/mpegpicture.c    			\
			libavcodec/mpegutils.c    				\
			libavcodec/mpegvideo.c    				\
			libavcodec/mpegvideodata.c    			\
			libavcodec/mpegvideodsp.c    			\
			libavcodec/mpegvideoencdsp.c    		\
			libavcodec/mpegvideo_enc.c    			\
			libavcodec/mpegvideo_motion.c    		\
			libavcodec/mpeg_er.c    				\
			libavcodec/qpeldsp.c    				\
			libavcodec/ratecontrol.c    			\
			libavcodec/rl.c    						\
			libavcodec/tiff_common.c    			\

AVCODEC_MJPEG_X86_FILES := \
			libavcodec/x86/constants.c    			\
			libavcodec/x86/hpeldsp_init.c    		\
			libavcodec/x86/mpegvideo.c    			\
			libavcodec/x86/mpegvideodsp.c    		\
			libavcodec/x86/mpegvideoenc.c    		\
			libavcodec/x86/mpegvideoencdsp_init.c   \
			libavcodec/x86/qpeldsp_init.c   		\

AVCODEC_MJPEG_ARM_FILES := \
			libavcodec/neon/mpegvideo.c    			\

